- id: cmake-format
  name: cmake-format
  description: cmake-format can format your listfiles nicely so that they don't look like crap.
  entry: cmake-format --in-place
  language: python
  types: [cmake]

- id: cmake-lint
  name: cmake-lint
  description: cmake-lint will check your listfiles for style violations, common mistakes, and anti-patterns.
  entry: cmake-lint
  language: python
  types: [cmake]
